### ISSUE TITLE
named fails to start on boot due to no interfaces were up to this time

### ISSUE THREAD

**Issue by toad42** [openwrt/packages#1044]
named fails to start on boot because no interfaces were up to this time.
It needs a rewrite of the start script to recognize interface changes, maybe I try it.

I workaround this for now with a sleep 10 in the start script and adding "interface-interval 1;" in the "named.conf".

**Comment by nmeyerhans** [comment]
I could be mistaken, but I think hotplug scripts are the appropriate fix here. Something like the following in /etc/hotplug.d/iface seems to work:

```
NAME=named

[ "$ACTION" = "ifup" -a "$INTERFACE" = "lan" ] && {
    logger -p user.notice "Restarting $NAME due to $ACTION $INTERFACE"
    /etc/init.d/$NAME restart
} &
```

On the other hand, I don't see why this should be necessary. At the very least `lo` should be up before named tries to start, due to boot script ordering.

**Comment by diizzyy** [comment]
@nmeyerhans 
Still relevant or can we close this?

**Comment by nmeyerhans** [comment]
Yeah, let's close. A lot of time has passed and there haven't been any additional reports or followups to this issue, and as I stated previously, I believe that the order of the init script execution should ensure that at least `lo` is up before named.
