### ISSUE TITLE
pip: Update to 20.0.2

### ISSUE THREAD

**Issue by aparcar** [openwrt/packages#11747]
Maintainer: @jefferyto 
Environment: global

Description:

Please update `pip` to the latest version. I'm currently trying to port `matrix-synapse` and it requires `pip` in version 20.x.x

**Comment by BKPepe** [comment]
`pip` is bundled in Python[3]. In Python 3.8.2, which was released in February, there is pip 19.2.3. You can ask Python developers why they didn't include pip 20.xx, which was released in January. I am not sure if I see a reason to update it here as this is handled by upstream and they update it on regular basis. We would diverge from that because of just one package, which you want to port. And updated pip will be for everyone and it might come with some issues. I don't think it's worth the risk.

Maybe @jefferyto has a different opinion than me.

**Comment by aparcar** [comment]
Thank you that's a perfect explanation! Ill ask upstream, was not aware that it is glued together!

**Comment by jefferyto** [comment]
I had a similar thought in #9541.

I think the versions of pip and setuptools bundled with Python are meant to bootstrap a new install (from source). After the initial installation, pip and setuptools can be updated (via pip), independent of Python. So I think there is more incentive for the core Python developers to bundle stable versions of pip and setuptools rather than the latest versions (which the user can choose to upgrade to later).

On the target side, I can see how some people may want the latest versions. On the host side though I think we would need a substantial reason to justify the added complexity.

On matrix-synapse, I'm not really sure why they would need a specific version of pip, or any version of pip since it is usually run by the user directly to install/upgrade Python packages. Do you have any error messages or additional information on their use of pip?

**Comment by aparcar** [comment]
Sorry wrong information, a much older `pip` versions seems fine

https://github.com/matrix-org/synapse/blob/master/INSTALL.md#troubleshooting-installation
