### ISSUE TITLE
List of "problematic" architectures

### ISSUE THREAD

**Issue by aparcar** [openwrt/packages#12968]
Hi, I'm currently building a CI which tests changed packages for multiple architectures. I'm not familiar with the lower level implementation of these architectures, but understand that a package may compile fine on one but break badly on another architecture. Could someone please help with with a short list of top 5 popular and top 5 breaking architectures to test within the CI?

**Comment by neheb** [comment]
ARC is a constant source of breakage since it uses a different libc (uClibc-ng).
PowerPC occasionally breaks, either because of no FPU or because of -lssp_nonshared
ARM64 has issues with PIC.
x86_64 is used by @stintel , who constantly complains of his builds being broken.
some of the older ARM platforms break sometimes.

**Comment by aparcar** [comment]
Amazing that's what I wanted to know :)!

**Comment by neheb** [comment]
ARM64 fails occasionally with PKG_ASLR_PIE. Not sure if that can be turned on.

It would be great to also compile without deprecated OpenSSL APIs if possible.

**Comment by aparcar** [comment]
> It would be great to also compile without deprecated OpenSSL APIs if possible.

Not sure how to do that. I'm currently working on a CI for openwrt.git, however it could be used for packages.git, too.

**Comment by neheb** [comment]
It’s a Kconfig option. OPENSSL_WITH_DEPRECATED I believe.

**Comment by neheb** [comment]
Not valid anymore I believe.
