### ISSUE TITLE
daemon.err dnsmasq[15236]: failed to send packet: Permission denied

### ISSUE THREAD

**Issue by snakwu** [openwrt/packages#13970]
Sat Nov 21 00:17:10 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:10 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:17 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:17 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:30 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:30 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:43 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:43 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:57 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:17:59 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:18:10 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied
Sat Nov 21 00:18:10 2020 daemon.err dnsmasq[15236]: failed to send packet: Permission denied

**Comment by BKPepe** [comment]
Hello @snakwu,

You posted here logs from dnsmasq, but we don't know which version of OpenWrt are you using. It would be good to know at least some more details which lead to this error together to know which router do you have.

Anyway, I am marking this issue as Invalid because dnsmasq is not present in packages repository and it comes from OpenWrt main repository.
