### ISSUE TITLE
keepalived: Back port security parameters fixes to v19.07

### ISSUE THREAD

**Issue by pgaufillet** [openwrt/packages#14648]
Maintainer: @feckert
Environment: mvebu-cortexa9-linksys_wrt3200acm, v19.07.6

Description: commits 1b1ba71 and a8a1fbf should be back ported to v19.07.

**Comment by feckert** [comment]
You are right. I also have the problem with the non existing /run directory. I already fixed this in my own build, so it was no longer on my radar. :+1:
I have staged a pullrequest to fixes this and the commits https://github.com/openwrt/packages/commit/1b1ba710632f8f4850f02c22e83734a6c8b5c41a and https://github.com/openwrt/packages/commit/a8a1fbfa0da2676583f0289e7ed2806a3191800c. I have to adjust commit https://github.com/openwrt/packages/commit/a8a1fbfa0da2676583f0289e7ed2806a3191800c so this one applies correctly. Because there where some config changes.
I am therefore not sure if this is correct. Unfortunately, I don't have a setup running at the moment to test this. Can you please check if the configuration is generated correctly?

**Comment by pgaufillet** [comment]
I have struggled to merge the PR in my workspace with deceiving results (I think I applied it incorrectly to my source tree), but that said I don't see any difference between this PR and the patched version I am running. I think you can proceed.

**Comment by feckert** [comment]
Is fixed with merge https://github.com/openwrt/packages/commit/8c63f6331cb648557ecaae874de00d7ceb782eae
