### ISSUE TITLE
please add pptpd to the 15.05 branch

### ISSUE THREAD

**Issue by duvi** [openwrt/packages#1477]
It was moved to github after the 15.05 branch was forked, so it's missing from there.

Thank you!

**Comment by axet** [comment]
`git log --all -- net/pptpd` shows Jul 13 2015 this files exists, then it is gone.

even `git log --all --diff-filter=D --summary shows no pptpd deletion. bug?

**Comment by yousong** [comment]
I guess that it's because `pptpd` was moved from `oldpackages` feed after creation of branch `for-15.05`, thus it's not there in `for-15.05`, nor `oldpackages`, yet it's part of `master` branch here.

`git log --all` will list history reachable from all tips from `refs/`.  `git branch --contains=<commit-id>` should confirm this.

**Comment by lperkov** [comment]
pushed.
