### ISSUE TITLE
copy of /etc/unbound/unbound.conf to /var/lib/unbound/ gets overwritten

### ISSUE THREAD

**Issue by vollkommenheit** [openwrt/packages#14909]
Package: unbound-daemon
Version: 1.13.1-1 and maybe older too
Depends: Depends: libc, ca-bundle, libopenssl1.1, libunbound
Status: install user installed
Section: net
Architecture: mips_24kc

Maintainer: @EricLuehrsen
Environment: Seen on ramips-mt7621 but *not* on ath79-generic-netgear_wndr3800

Description:
On the new ramips-mt7621 based router running 
OpenWrt SNAPSHOT r15963-512229ce49 I'm setting up,  /usr/lib/unbound/unbound.sh does not copy /etc/unbound/unbound.conf to /var/lib/unbound/, or alternatively, that it does so, only to have the unbound.conf from /etc/unbound/ overwritten later by the stock unbound.conf generated by /etc/init.d/unbound. This happens regardless of whether I first remove the generated unbound.conf or manually copy over /etc/unbound/unbound.conf first. 

If I replicate the "cp -p $UB_ETCDIR/*.conf $UB_VARDIR/" block within /usr/lib/unbound/unbound.sh, putting it after the last "if...fi" but before "resolv_setup", then the unbound.conf from /etc/unbound/ survives in /var/lib/unbound/ after each /etc/init.d/unbound start or restart.

I don't have this issue on ath79-generic-netgear_wndr3800 running OpenWrt SNAPSHOT r15949-ce8b535ed3 (which is only a few days newer) or any snapshot versions before.

Also, would it make sense to have /etc/init.d/unbound or /usr/lib/unbound/unbound.sh  copy /etc/unbound/*pem and /etc/unbound/*key to /var/lib/unbound/ if the latter files do exist to /etc/unbound/? What I've been running into is, after flashing each snapshot sysupgrade image, with /etc/unbound in my /etc/sysupgrade.conf, the freshly installed unbound-daemon invariably fails to start, due to my /etc/unbound/unbound.conf pointing to those .pem and .key files, but none were found in (copied to) /var/lib/unbound/.

**Comment by EricLuehrsen** [comment]
Yes that is the design intent. If you use `manual_conf` in UCI, then your `/etc/unbound/unbound.conf` is used. Otherwise UCI writes a new one. If you want to amend the UCI generated one, then you can add to `/etc/unbound/unbound_[srv/ext].conf.` Unbound loads certificates before it drops root privleges, so they can (should) remain in `/etc/...` or some more secure area. The only exception is the DNS root key which is regularly maintained using RFC5011. That would burn ROM so it needs to be in `/var/...` and copied back at a much slower rate.

**Comment by vollkommenheit** [comment]
Ah, I see. I need to add:
>uci set 'unbound.@unbound[0].manual_conf=1'
>uci commit

to my sysupgrade routine then.
