### ISSUE TITLE
mwan3 ping checks depend on DNS

### ISSUE THREAD

**Issue by davidelang** [openwrt/packages#14924]
Maintainer: @\feckert
Environment: Turris omni openwrt 19.07 mwan3 version 2.8.15-1

Description:
the ping checks don't have -n (skip DNS lookups), so when there is an outage on the main link, DNS may fail for a bit before lookups succeed on the second link. During this time the ping checks on the second link can also fail, causing it to be marked down.

adding -n to the ping command line eliminates this failure mode

**Comment by jamesmacwhite** [comment]
This will be an issue for Busybox ping, as it doesn't have the `-n` flag. `iputils-ping` will likely support this, but it's not a strict requirement of mwan3.

**Comment by jamesmacwhite** [comment]
Ping for @feckert, as the maintainer info has a typo.

**Comment by aaronjg** [comment]
It looks like busy box ping ignores the -n option, so we could add it for iputils ping and it will be ignored when iputils ping is not installed.

https://git.busybox.net/busybox/tree/networking/ping.c?id=9b6bcfda0e11c0e73a966a77110f6c68425cff34#n401

@davidelang Care to make a pull request?

**Comment by davidelang** [comment]
I don't know how to tell which ping is being used, so if you don't mind, I'll watch the commit and learn rather than taking more maintainer time with my fumbling :-/

**Comment by aaronjg** [comment]
It should be just these lines here:

https://github.com/openwrt/packages/blob/267b65ad9f74c854e790f0771e280b763df5f07e/net/mwan3/files/usr/sbin/mwan3track#L245

https://github.com/openwrt/packages/blob/267b65ad9f74c854e790f0771e280b763df5f07e/net/mwan3/files/usr/sbin/mwan3track#L250

Happy to help and review the P/R if you are interested in contributing. Otherwise, I can get to it once I finish debugging an LT2P mwan3 issue that I am working on.

**Comment by davidelang** [comment]
that's equivalent to where I added the -n on my earlier version, but how do you make it conditional on what version of ping is being run? or does the busybox version ignore the -n so it's safe to have there in any case?

**Comment by aaronjg** [comment]
> does the busybox version ignore the -n so it's safe to have there in any case?

Exactly. Busybox ping ignores the -n, so it can safely be added regardless of which ping version is used.

**Comment by jamesmacwhite** [comment]
Good to know about Busybox! The only other thing I remember about iputils-ping for 19.07 is the package is super old, in snapshot its been split from the main source and much more up to date, but I thought using the 2010 version caused issues on 19.07 once installed. Unless maybe the recent kernel patch resolved the issues that occurred with iputils-ping.

**Comment by feckert** [comment]
@aaronjg done

**Comment by BlessDeix92** [comment]
I know this issue is closed but I have some valuable info regarding this subject, which is that this issue is probably moot.

The dnsmasq DNS server/client in OpenWRT has the "allservers" option set by default. Note that the wiki currently says this option is set "0" default, but it's wrong. This option is, in fact, set on/active by default, which means that all upstream DNS servers get queried and the first received reply is used.

Further, when dnsmasq sends these queries, it send them out of the associated interfaces the DNS servers were configured for.

The result is that even if your default network route is down, as long as one of them is up, you should get a DNS reply back, even without mwan3 installed. This can be pretty confusing behavior while troubleshooting!

This can all be verified by doing a "tcpdump -i any dst port 53 &" and then doing a nslookup.
