### ISSUE TITLE
[19.07]ath10k-ct: update to latest version

### ISSUE THREAD

**Issue by openwrt-diy** [openwrt/packages#15540]
@paulfertser @hauke
The new version of ath10k-ct has solved many problems, can you update it? I am now using ath10k-ct to open the SSID and the wireless rate is very unstable, and the network has been in a circle.

openwrt-19.07
PKG_NAME:=ath10k-ct
PKG_RELEASE=1
PKG_LICENSE:=GPLv2
PKG_LICENSE_FILES:=
PKG_SOURCE_URL:=https://github.com/greearb/ath10k-ct.git
PKG_SOURCE_PROTO:=git
PKG_SOURCE_DATE:=2019-09-09
PKG_SOURCE_VERSION:=5e8cd86f90dac966d12df6ece84ac41458d0e95f
PKG_MIRROR_HASH:=dc1097f3a7b4b7e346918f206746d00a0b7df07ae3be9b89be55dfaef3cbbe45

ath10k-ct: workaround TX rate code firmware bug
https://github.com/greearb/ath10k-ct/pull/129

PKG_NAME:=ath10k-ct
PKG_RELEASE=1
PKG_LICENSE:=GPLv2
PKG_LICENSE_FILES:=
PKG_SOURCE_URL:=https://github.com/greearb/ath10k-ct.git
PKG_SOURCE_PROTO:=git
PKG_SOURCE_DATE:=2020-10-08
PKG_SOURCE_VERSION:=1d28d176e5b6e63a6583f497adf68e1d9c1dc962
PKG_MIRROR_HASH:=f611762647822742f7c8f9da242e33d9bf6da0a14976b87408af28f280802ae0

**Comment by BKPepe** [comment]
Hello @openwrt-diy,

Thank you for creating this issue in the `packages` repository. Unfortunately, you created it in the wrong repository because there are community-maintained packages, which are not part of the core repository. In [the core repository](https://github.com/openwrt/openwrt) you can find ath10k, where it can be updated.

You can follow an article in documentation [reporting bugs](https://openwrt.org/bugs), giving you more insight into which packages belong.

If you want to have it updated, you can send a pull request there or send the patch by using email to [openwrt-devel](https://lists.openwrt.org/pipermail/openwrt-devel/) mailing list.
