### ISSUE TITLE
libiwinfo20210430 - from nand/ath79 is missing for 	OpenWrt 21.02.0-rc3

### ISSUE THREAD

**Issue by Psilovybin** [openwrt/packages#16014]
Not a huge issue but just a missing package

**Comment by BKPepe** [comment]
Fixed by these two commits https://github.com/openwrt/openwrt/commit/d723002d84e25d18b7e225d5e6f2810875d052c7 and https://github.com/openwrt/openwrt/commit/b0424190efe0fa4de4be6c1b59107e0881a39950. As you can see these commits are in openwrt/openwrt, thus means that your report here in packages repository is invalid. Packages repository is for community maintained packages.
