### ISSUE TITLE
dnscrypt-proxy 1.6.0

### ISSUE THREAD

**Issue by freegigi** [openwrt/packages#1602]
dnscrypt-proxy is two versions behind in chaos calmer branch. the latest release is 1.6.0.
i tried using 1.4.3 CC, but it kept crashing. 1.6.0 on a trunk build works fine.

Thank you.

**Comment by KanjiMonster** [comment]
@damianorenfer

**Comment by damianorenfer** [comment]
Thanks for reporting. Could you provide more information about the crash please ? 

It is not the lastest version, but as I'm not an OpenWrt expert I don't know the versionning workflow... Should I update the version in for-15.05 ? Or does someone else syncronize with master branch ?

**Comment by damianorenfer** [comment]
Found an answer CONTRIBUTINB.md : 
>Do NOT add new packages and do NOT do major upgrades of packages here

**Comment by damianorenfer** [comment]
@sbyx or @thess : Is there a way to update to 1.6 in 15.05 branch ?

Thanks

**Comment by thess** [comment]
Submit a PR on the for-15.05 branch. Include [for-15.05] in the request title. Give an explanation for the necessity to do the upgrade.

But first... Test the fix in the 15.05 environment

**Comment by rugk** [comment]
:+1: for updating. See: https://forum.openwrt.org/viewtopic.php?pid=317892

**Why update to 1.5.0?**
Because v1.50 dnscrypt supports ephemeral keys, which config option is already listed [in the wiki](https://wiki.openwrt.org/inbox/dnscrypt).

**Why update to v1.6.1?**
Because according to the [release notes](https://github.com/jedisct1/dnscrypt-proxy/releases/tag/1.6.1) a vulnerability was fixed there...

**Comment by thess** [comment]
Closing this - over a year old
