### ISSUE TITLE
"missing" package perlbase-hostname

### ISSUE THREAD

**Issue by sla-te** [openwrt/packages#16031]
https://openwrt.org/docs/guide-user/services/gitolite requests to install perlbase-hostname but it does not seem to be a package, was it renamed?

**Comment by BKPepe** [comment]
I did a short digging up, what happened with that package, but it seems that article is really old. The article's dependency was added somewhere in 2015, but the package is not present even old archives branches like ``for-14.07``, ``for-15.05``.

I am closing this issue. You can ask someone for help to port gitolite for [OpenWrt on forum](https://forum.openwrt.org/). `Gitolite` is not present in our repository and thus this issue is invalid.
