### ISSUE TITLE
frr: Lacking MD5 kernel support breaks frr (CONFIG_TCP_MD5SIG)

### ISSUE THREAD

**Issue by Knogle** [openwrt/packages#16702]
Maintainer: Lucian Cristian <lucian.cristian@gmail.com>
Environment: x86_64 OpenWrt 21.02-SNAPSHOT r16293-bf30ad1408
Description:

Ahoy ahoy.
I have been using quagga and frr for a long time, now i have upgraded to 21.02 and was wondering why my BGP sessions didn't come up anymore, and why i only get malformed TCP packets. It was difficult to troubleshoot. But i have found the reason.
I am using MD5 password authentication for my BGP peers which is quite essential, because due to my work for my ISP i'm allowed to have a CPE edge BGP peering with my ISP. Therefor password authentication is required.

I found out, the log messages i got are being caused by the lack of `CONFIG_TCP_MD5SIG=y` support in the current kernel. In case of the master branch it worked, because `CONFIG_TCP_MD5SIG` is being enabled, but for the stable 21.02 release it's not enabled, and has to be manually enabled using make kernel_menuconfig. It would be great to add this setting somehow to the dependencies for these packages, because the lack of MD5 support breaks frr, quagga, bird and some other packages.

```2021/09/24 12:49:16 BGP: can't set TCP_MD5SIG option on socket 13: Protocol not available
2021/09/24 12:49:20 BGP: sockopt_tcp_signature: setsockopt(12): Protocol not available
2021/09/24 12:49:20 BGP: can't set TCP_MD5SIG option on socket 12: Protocol not available
2021/09/24 12:49:21 BGP: sockopt_tcp_signature: setsockopt(13): Protocol not available
2021/09/24 12:49:21 BGP: can't set TCP_MD5SIG option on socket 13: Protocol not available
2021/09/24 12:49:25 BGP: sockopt_tcp_signature: setsockopt(12): Protocol not available
2021/09/24 12:49:25 BGP: can't set TCP_MD5SIG option on socket 12: Protocol not available
2021/09/24 12:49:26 BGP: sockopt_tcp_signature: setsockopt(13): Protocol not available
2021/09/24 12:49:26 BGP: can't set TCP_MD5SIG option on socket 13: Protocol not available
2021/09/24 12:49:30 BGP: sockopt_tcp_signature: setsockopt(12): Protocol not available
2021/09/24 12:49:30 BGP: can't set TCP_MD5SIG option on socket 12: Protocol not available
2021/09/24 12:49:31 BGP: sockopt_tcp_signature: setsockopt(13): Protocol not available
2021/09/24 12:49:31 BGP: can't set TCP_MD5SIG option on socket 13: Protocol not available
```

**Comment by micmac1** [comment]
CONFIG_TCP_MD5SIG was never enabled in any OpenWrt default kernel configuration. Even in master.

https://github.com/openwrt/openwrt/blob/master/target/linux/generic/config-5.10
https://github.com/openwrt/openwrt/blob/master/target/linux/generic/config-5.4

I didn't find any commit in history that changed that.

Checked FFR docs: https://docs.frrouting.org/en/latest/bgp.html

So I gather the below will not work with default kernel config:
`neighbor PEER password PASSWORD`

I've seen you plastered the forum with your requests already [here](https://forum.openwrt.org/t/config-tcp-md5sig-not-enabled-anymore-on-21-02-but-breaks-packages/107321), [here](https://forum.openwrt.org/t/config-tcp-md5sig-missing-bgp-connection-doesnt-work-anymore-after-upgrading-to-frr/107311) and [here](https://forum.openwrt.org/t/openwrt-21-02-0-first-stable-release/105395/233). I think a forum search would have revealed that other people discussed or brought up this same issue already [here](https://forum.openwrt.org/t/bgp-routing-peering-with-password-authentication/80310) and [here](https://forum.openwrt.org/t/help-creating-a-pr-to-add-a-kernel-feature-for-openwrt-bird/30775). So when you build yourself you can enable CONFIG_TCP_MD5SIG and then use it.

If you want you can send a patch to OpenWrt to get it enabled by default. See [Submitting Patches](https://openwrt.org/submitting-patches) on how to do that. I'd expect the OpenWrt maintainers would want to know why it should be enabled by default and whether it brings a noticeable size increase and if there are any pitfalls to be expected with it enabled. And if there are other configuration symbols this symbol depends on.

But this isn't an issue with the frr package, so this issue is misplaced in my opinion.
