### ISSUE TITLE
kmod-usb-net-ipheth: Patch for iOS 14+ devices

### ISSUE THREAD

**Issue by brenr** [openwrt/packages#17199]
Maintainer: `https://github.com/torvalds/linux/blob/master/drivers/net/usb/ipheth.c`

Environment:
open wrt machine's image: `openwrt-21.02.1-63eb93c5ac34-bcm27xx-bcm2711-rpi-4-ext4-factory`
iPhone iOS version: 15.1.1

Description:
See these proposed changes: https://github.com/openwrt/openwrt/commit/d0b8be75ff248b4cda009a6c1ce72eb0072c6f82

I see the MAC address of the iPhone in interfaces but an IP is not being assigned. Assigning a static IP for the eth1 interface to the iPhone's tethering subnet doesn't seem to help.

**Comment by BKPepe** [comment]
Hello,

Thank you for creating the issue. I saw the proposed changes, but these are included in OpenWrt 21.02.

Take a look at this commit:
https://github.com/openwrt/openwrt/commit/f64496f30f2ef97124dc4e13a48ee0de9d51832e

In any case, this issue was reported to the wrong repository. Feel free to check this out: https://openwrt.org/bugs , because ``kmod-usb-net-ipheth`` is not included in this repository, which you can check yourself by browsing source code. 

 Closing.
