### ISSUE TITLE
igmpproxy:Older version in opkg (0.2 vs 0.3)

### ISSUE THREAD

**Issue by alexknop** [openwrt/packages#17663]
Maintainer: @\ja-pa  
Environment: (OpenWrt 21.01)

Description:
Hello, 

I am wondering what it would take to get the updated package of igmpproxy (0.3) from its source [****](https://github.com/pali/igmpproxy)

There's an important commit in there which would allow me to pass SSDP packets (Needed for my project which is to have a Sonos speaker on a different VLAN than the Devices which have the Sonos controller app on them).

I am not sure how to put this updated package on my router, so am hoping someone here can do it and I can update via opkg.

Thanks in advance.

**Comment by BKPepe** [comment]
While checking your request, I see that package igmpproxy for OpenWrt 21.02 is located in [the main repository](https://github.com/openwrt/openwrt). You might want to consider submitting a pull request over there, and let's see if it gets updated. Most likely, only security updates will be accepted there, but you will see. :)

Anyway, this package was moved here for newer OpenWrt versions, and since OpenWrt 22.03, there is already version 0.3.
