### ISSUE TITLE
fwknopd - can't set working interface.

### ISSUE THREAD

**Issue by grissone** [openwrt/packages#1771]
When I try to change interface on where the demon has to listen to, default value appears on 'save and apply' (every time the demon restart).
I took a look on /etc/init.d/fwknopd and I saw that it's working well if I change the get_conf func with

if [ "uci get fwknopd.@access[0].PCAP_INTF" = ""]
Rather than
if [ 'uci get fwknopd.@access[0].PCAP_INTF' = ""]
Thx

**Comment by oneru** [comment]
@grissone Hey, sorry to take so long to look at this.  So, the issue is actually that the line you quoted looks in the access section, whereas PCAP_INTF is in the config section.  So as it is now, PCAP_INTF doesn't exist where this line is looking for it, so it always evaluates to true.  The single quote is correct. Once changed to a double quote, the uci command is never run, so it always evaluates to false.

I'll get this changed today. The corrected line is 
if [ 'uci get fwknopd.@config[0].PCAP_INTF' = ""]

**Comment by oneru** [comment]
I believe this issue was fixed with commit d83625938616d9bb165f9d8f8d856f218164ac8c

**Comment by dkadioglu** [comment]
Could this be backported to Chaos Calmer? I've applied the fix manually and it works as it should.

**Comment by oneru** [comment]
@sbyx This has been fixed for a while, just never got backported to CC, as it's not a security fix.  What's the policy on backports, is this worthy of getting cherrypicked?

**Comment by hnyman** [comment]
That is a small bug in the Openwrt scripts. Sure it can be backported to fix the package also in CC.

(I noticed that you have slightly tweaked the fix in the next version upgrade https://github.com/openwrt/packages/commit/8cc558b8a36eabbd21937092e6542dc36e5b6668 , so maybe that should be backported instead of cherrypicking just this?)

**Comment by dkadioglu** [comment]
+1 for cherrypicking 8cc558b. Still I would be happy if this small fix could be backported. Can I somehow help? Should I create a pull request?

**Comment by oneru** [comment]
*adds this to calendar for this afternoon*

**Comment by oneru** [comment]
This fix is now in for-15.05.  Suggest close the issue.
