### ISSUE TITLE
vpn-policy-routing: VPN Policies create iptables on OpenWRT 22.03

### ISSUE THREAD

**Issue by jjpinom** [openwrt/packages#19064]
Maintainer: @\stangri
Environment: 22.03

Description:

vpn-policy-routing is creating iptables and not nftables it seems to be working, but the firewall status section alerts about legacy iptables entries

**Comment by jjpinom** [comment]
Thanks for taking this. 

Just a comment. I use also dnsmasq ipset functionality. I don't know if ipset and nftables work together.

Best regards.

**Comment by stangri** [comment]
I've updated the [vpn-policy-routing README](https://docs.openwrt.melmac.net/vpn-policy-routing/) and also the README for the new package -- [pbr](https://docs.openwrt.melmac.net/pbr/).
I'm closing this, as this is "wont't fix" for vpn-policy-routing since the switch to nft is going to be implemented in a different package.
