### ISSUE TITLE
update      zstd  1.5.5

### ISSUE THREAD

**Issue by Potterli20** [openwrt/packages#22308]
https://github.com/facebook/zstd/releases/tag/v1.5.5

**Comment by BKPepe** [comment]
Feel free to submit pull request for it.

**Comment by BKPepe** [comment]
In that case, reach upstream to get this working. Zstd in our repository does not have any maintainer, so someone from the OpenWrt community should step it and update it. Nothing what we can do here. There are plenty of issues here and we need to deal with that one by one. 

There isn't mentioned any CVEs between 1.5.2 (which we have here) and 1.5.5.

This is feature request and because of that closing. You might want to ask someone at OpenWrt forum or use IRC channels, which are available to use.
