### ISSUE TITLE
commit permissions

### ISSUE THREAD

**Issue by systemcrash** [openwrt/packages#23552]
Would like to help with review and commits to the packages repo also so I'd like to request commit access to this repo.

Active in the luci repo, but need to nudge things along in openwrt and packages also quite frequently.

**Comment by BKPepe** [comment]
I wonder, what is so urgent to have commit permissions? I have seen only your recent commits to p910nd and since you have not reviewed other packages, etc. I don't see the point currently that you would have commit permissions.

If I see more activity or you will be maintaining and keeping packages up to date, why not. Sadly thats not happening currently.
