### ISSUE TITLE
softethervpn5 5.02.5182 released, please update.

### ISSUE THREAD

**Issue by nginLTD** [openwrt/packages#23759]
https://github.com/SoftEtherVPN/SoftEtherVPN/releases/tag/5.02.5182

Hope to update soon.

**Comment by BKPepe** [comment]
Any pull requests are appreciated. :) If you want to help and update it faster, you can open it and try to do it yourself.
Is there something urgent that needs to be updated to the latest version? In the release, I don't see that there is a security vulnerability to be fixed, and based on https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1966, I see that the fix is related to Windows.

**Comment by BKPepe** [comment]
Updated in https://github.com/openwrt/packages/pull/24359
