### ISSUE TITLE
Not detecting a lack of Internet

### ISSUE THREAD

**Issue by RChadwick7** [openwrt/packages#23968]
Using the latest Travelmate, it will stay on an XFinity hotspot even if there is no Internet. For whatever reason, Xfinity keeps deleting this hotspot and the generic portal script doesn't work. There are other, less desirable yet mostly working hotspots available but Travelmate stays on the non working access point.
```

**Comment by dibdot** [comment]
Check the online available readme (linked in the LuCI app), esp. the 'trm_netcheck' option.

**Comment by hackerb9** [comment]
> Check the online available readme (linked in the LuCI app), esp. the 'trm_netcheck' option.

I think a better solution is to add a bad access point like "xfinity" to the list of stations manually and click "On/Off" to disable it. (Presuming you don't actually use xfinity).

Netcheck is dangerous to enable since it completely disables stations which lack Internet instead of marking them to be checked again later. That means a good station which had a temporary network outage will not be used even when it does have Internet. Undoing the problem requires the user to login to OpenWRT to re-enable the station manually.

@dibdot: Do I have it correct how `trm_netcheck` works?
