### ISSUE TITLE
pptpd: build error: implicit declaration of function 'logwtmp'

### ISSUE THREAD

**Issue by M95D** [openwrt/packages#25207]
Maintainer: none, last update by @ptpt52 last week, commited by @hnyman
Environment: armv7, mvebu Armada 385, Turris Omnia, OpenWrt git main

Description:
```
make[5]: Entering directory '/var/tmp/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/pptpd-1.5.0/plugins'
ccache arm-openwrt-linux-muslgnueabi-gcc -o pptpd-logwtmp.so -shared -pipe -fno-caller-saves -fno-plt -pipe -fhonour-copts -mfloat-abi=hard -fmacro-prefix-map=/var/tmp/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/pptpd-1.5.0=pptpd-1.5.0 -ffunction-sections -fdata-sections -flto=auto -fno-fat-lto-objects -Wformat -Werror=format-security -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -I.. -I../../include -fPIC pptpd-logwtmp.c -lutil
pptpd-logwtmp.c: In function 'ip_up':
pptpd-logwtmp.c:54:3: error: implicit declaration of function 'logwtmp' [-Wimplicit-function-declaration]
   54 |   logwtmp(ifname, user, pptpd_original_ip);
      |   ^~~~~~~
make[5]: *** [Makefile:19: pptpd-logwtmp.so] Error 1
```

**Comment by M95D** [comment]
PS:
I've accepted the ideea that nobody does manual tests anymore, but I'm really interested to know why this wasn't caught by the automated tests.

**Comment by hnyman** [comment]
> I'm really interested to know why this wasn't detected by the automated tests.

Maybe because buildbot builds it quite happily, also for the target that you are using.
It is not in the faillogs...
https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a9_vfpv3-d16/packages/

...and can be found from the download directory, built two days ago for the last time:
pptpd_1.5.0-r1_arm_cortex-a9_vfpv3-d16.ipk | 31.0 KB | Thu Oct 24 23:38:33 2024
https://downloads.openwrt.org/snapshots/packages/arm_cortex-a9_vfpv3-d16/packages/pptpd_1.5.0-r1_arm_cortex-a9_vfpv3-d16.ipk

**Comment by M95D** [comment]
Yes, that's what I'm talking about.
I can reproduce the error with a fresh clone of git repo, with only my .config added. Why is it that automated builds *don't* fail?
[config.txt](https://github.com/user-attachments/files/17531676/config.txt)

**Comment by brada4** [comment]
Run diffconfig.sh please

**Comment by neheb** [comment]
logwtmp being implicit becomes an error with GCC14.
