### ISSUE TITLE
Sorry - not an issue

### ISSUE THREAD

**Issue by zyxmon** [openwrt/packages#3339]
Deleted

**Comment by commodo** [comment]
Well, yes & no.
Python can build without libncurses(w) [if I remember correctly] ; I think it's there as a copy-paste fluke.
In that sense, if libncursesw is present it will use that, otherwise libncurses, and then finally it won't build it.

I will admit, it's not particularly correct.
We could remove it, or fix it [add a host-side libncurses build].
Though, I am a bit more inclined to remove it.

What error do you see ?

**Comment by commodo** [comment]
ah ; just noticed the rename of the topic

**Comment by zyxmon** [comment]
@commodo - we have removed these lines in Entware. No problems.
