### ISSUE TITLE
btrfs-progs: needs a new maintainer (in case anyone is actually using it)

### ISSUE THREAD

**Issue by dangowrt** [openwrt/packages#4491]
I haven't been using btrfs for a very long time and hence removed myself from being the maintainer of btrfs-progs. btrfs is being used by the [Turis Omnia](https://omnia.turris.cz/en/) hence maybe @miska @shenek @Cynerd are good candidates to take over maintainership of btrfs-progs.

**Comment by diizzyy** [comment]
I think we should decide on a placeholder for that entry.
Needs maintainer <no-maintainer@packages.openwrt.org> or whatever

**Comment by mhei** [comment]
Maintainership was taken over by @neheb in #5154, so we can close this.

**Comment by dangowrt** [comment]
https://github.com/openwrt/packages/pull/8339

**Comment by BKPepe** [comment]
I haven't noticed this issue until now. 

As you said Turris Omnia indeed uses BTRFS and it will be good if we (speaking as a member of Turris Team) can take maintainer of this package. Thank you guys for suggestions!

We spoke together and I'm not sure if I currently understand issues related to BTRFS and I think it will be really hard for me to fix some issues, which may appear about it. That's why I have suggested @Cynerd to take package maintainership of this package and most probably he will prepare a pull request. :-)

**Comment by dangowrt** [comment]
@BKPepe Thank you for getting involved.
Note that the bug was closed for quite a while @neheb was doing the job and only re-opened now as he dropped maintainership.
@Cynerd Please make a PR adding yourself (full first and last name) as the `PKG_MAINTAINER:=` of the package.
