### ISSUE TITLE
php7 - imagemagick module?

### ISSUE THREAD

**Issue by eliz82** [openwrt/packages#5351]
Maintainer: @mhei ?
Environment: Entware / Voxel Firmware / Netgear R7800

Description:
any chance to get the imageck (imagemagick) PHP module? https://github.com/mkoppanen/imagick
it seem they made it compatible with php7 starting with imageck 3.4.x version.

this module is more more future rich then php GD module and more better then using external imagemagick using PHP "exec" function 
http://php.net/manual/en/book.imagick.php

**Comment by pprindeville** [comment]
Why would anyone need this on an embedded firewall/router?

**Comment by jow-** [comment]
Charting, traffic stats, pie charting quotas, ...

The same could bes asked about PHP ;)

**Comment by pprindeville** [comment]
Fair enough.

**Comment by mhei** [comment]
First step should be to (re-)integrate the library because the pecl extension would need it as dependency when I see this correctly. When the library is added, then we can talk about packaging this new pecl extension and I can take maintainership of the new pecl package, so I'll assign this issue to myself, to keep it on my radar. But I do not intend to become maintainer of imagemagick library, so volunteers are welcome :smile:

**Comment by mhei** [comment]
I'm closing this issue: as long as nobody wants to maintain imagemagick library for OpenWrt, we do not have package requirements satisfied.

**Comment by flyn-org** [comment]
@crisc82 and @mhei, please see https://github.com/openwrt/packages/pull/14286. This is useful for running NextCloud on OpenWrt.
