### ISSUE TITLE
miniupnpd not show router with ipv4, ipv6 - works

### ISSUE THREAD

**Issue by rasdotsu** [openwrt/packages#6530]
Hello,

miniupnpd - 2.1-1

openwrt-18.06.0-rc2-ar71xx-generic-tl-wr1043nd-v2-squashfs-sysupgrade

cat /etc/config/upnpd 

config upnpd 'config'
        option download '1024'
        option upload '512'
        option internal_iface 'lan'
        option external_iface 'wan'
        option port '5000'
        option upnp_lease_file '/var/run/miniupnpd.leases'
        option enabled '1'
        option uuid '37405787-6edf-4bf5-96db-d40b6e20dbf9'

config perm_rule
        option action 'allow'
        option ext_ports '1024-65535'
        option int_addr '0.0.0.0/0'
        option int_ports '1024-65535'
        option comment 'Allow high ports'

config perm_rule
        option action 'deny'
        option ext_ports '0-65535'
        option int_addr '0.0.0.0/0'
        option int_ports '0-65535'
        option comment 'Default deny'

upnp not shown or detectd via ipv4, if ipv6 used - works and found.

ipv4 search:

./listdevices 
searching all UPnP devices
no device found.

ipv6 search:

./listdevices -6
searching all UPnP devices
  1: uuid:37405787-6edf-4bf5-96db-d40b6e20dbfa       
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbfa
  2: uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb       
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb
  3: urn:schemas-upnp-org:device:WANDevice:2         
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbfa::urn:schemas-upnp-org:device:WANDevice:2
  4: urn:schemas-upnp-org:service:WANIPConnection:2  
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb::urn:schemas-upnp-org:service:WANIPConnection:2
  5: urn:schemas-upnp-org:service:DeviceProtection:1 
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9::urn:schemas-upnp-org:service:DeviceProtection:1
  6: urn:schemas-upnp-org:service:WANIPv6FirewallControl:1
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb::urn:schemas-upnp-org:service:WANIPv6FirewallControl:1
  7: urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbfa::urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
  8: urn:schemas-upnp-org:service:WANPPPConnection:1 
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb::urn:schemas-upnp-org:service:WANPPPConnection:1
  9: urn:schemas-upnp-org:service:Layer3Forwarding:1 
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9::urn:schemas-upnp-org:service:Layer3Forwarding:1
 10: uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9       
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9
 11: upnp:rootdevice                                 
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9::upnp:rootdevice
 12: urn:schemas-upnp-org:device:InternetGatewayDevice:2
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9::urn:schemas-upnp-org:device:InternetGatewayDevice:2
 13: urn:schemas-upnp-org:device:WANConnectionDevice:2
     http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml
     uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb::urn:schemas-upnp-org:device:WANConnectionDevice:2

http://[fd69:b7a7:ac55::1]:5000/rootDesc.xml :
 1: uuid:37405787-6edf-4bf5-96db-d40b6e20dbfa
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbfa
 2: uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb
 3: urn:schemas-upnp-org:device:WANDevice:2
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbfa::urn:schemas-upnp-org:device:WANDevice:2
 4: urn:schemas-upnp-org:service:WANIPConnection:2
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb::urn:schemas-upnp-org:service:WANIPConnection:2
 5: urn:schemas-upnp-org:service:DeviceProtection:1
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9::urn:schemas-upnp-org:service:DeviceProtection:1
 6: urn:schemas-upnp-org:service:WANIPv6FirewallControl:1
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb::urn:schemas-upnp-org:service:WANIPv6FirewallControl:1
 7: urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbfa::urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
 8: urn:schemas-upnp-org:service:WANPPPConnection:1
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb::urn:schemas-upnp-org:service:WANPPPConnection:1
 9: urn:schemas-upnp-org:service:Layer3Forwarding:1
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9::urn:schemas-upnp-org:service:Layer3Forwarding:1
10: uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9
11: upnp:rootdevice
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9::upnp:rootdevice
12: urn:schemas-upnp-org:device:InternetGatewayDevice:2
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbf9::urn:schemas-upnp-org:device:InternetGatewayDevice:2
13: urn:schemas-upnp-org:device:WANConnectionDevice:2
    uuid:37405787-6edf-4bf5-96db-d40b6e20dbfb::urn:schemas-upnp-org:device:WANConnectionDevice:2

**Comment by SirDMZ** [comment]
Can confirm. Disabled IPv6 on lan interface and restarted miniupnp, now it works.

**Comment by diizzyy** [comment]
@ldir-EDB0

**Comment by ldir-EDB0** [comment]
No idea.  And the reports are confusing, one says disabled IPv6 and it works, the other says enabled ipv6 and it works.  I don't know what this './listdevices' is?

Is there a difference between the ports miniupnpd is listening to one a working v non working router?  Proving it at least thinks it's listening would be a start 'netstat -nap | grep miniupn'

**Comment by SirDMZ** [comment]
##Bad:
root@OpenWrt:~# netstat -nap | grep miniupn
tcp        0      0 :::5000                 :::*                    LISTEN      31306/miniupnpd
udp        0      0 172.30.200.1:55072      0.0.0.0:*                           31306/miniupnpd
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           31306/miniupnpd
udp        0      0 172.30.200.1:5351       0.0.0.0:*                           31306/miniupnpd
udp        0      0 :::46344                :::*                                31306/miniupnpd
udp        0      0 :::1900                 :::*                                31306/miniupnpd
udp        0      0 :::5351                 :::*                                31306/miniupnpd
unix  2      [ ]         DGRAM                    457704 31306/miniupnpd

##Good:
root@OpenWrt:~# netstat -nap | grep miniupn
tcp        0      0 :::5000                 :::*                    LISTEN                                                   32152/miniupnpd
udp        0      0 172.30.200.1:57405      0.0.0.0:*                                                                        32152/miniupnpd
udp        0      0 0.0.0.0:1900            0.0.0.0:*                                                                        32152/miniupnpd
udp        0      0 172.30.200.1:5351       0.0.0.0:*                                                                        32152/miniupnpd
udp        0      0 :::37964                :::*                                                                             32152/miniupnpd
udp        0      0 :::1900                 :::*                                                                             32152/miniupnpd
udp        0      0 :::5351                 :::*                                                                             32152/miniupnpd
unix  2      [ ]         DGRAM                    461035 32152/miniupnpd



No real difference there.


Syslog doesn't show anything useful. In both cases it has:
Sun Jul 22 18:50:26 2018 daemon.notice miniupnpd[442]: shutting down MiniUPnPd
--
  | Sun Jul 22 18:50:27 2018 daemon.notice miniupnpd[830]: HTTP listening on port 5000
  | Sun Jul 22 18:50:27 2018 daemon.notice miniupnpd[830]: HTTP IPv6 address given to control points : [fd23:c778:59e1::1]
  | Sun Jul 22 18:50:27 2018 daemon.notice miniupnpd[830]: Listening for NAT-PMP/PCP traffic on port 5351

I tried disabling pmp and upnp one at a time to see where the issue is. The issue appears to be in upnp.

**Comment by ldir-EDB0** [comment]
I'm afraid I have absolutely no idea how to progress this.

**Comment by rasdotsu** [comment]
listdevices - tool from miniupnpc-2.1
miniupnpd listen only ipv6 and not ipv4

**Comment by ldir-EDB0** [comment]
ok so I got 'listdevices' to build on my mac and it lists many devices including my openwrt router when run as 'listdevices',  it lists *only* my router when run as 'listdevices -6'.  I have an ancient windows server box that gets quite upset if it can't talk ipv4 to the upnp gateway and that appears to be happy.  So this smells like a config issue rather than any fundamental 'miniupnpd is broken'.  /etc/config/upnpd is effectively a wrapper around /var/etc/miniupnpd.conf, which is generated by the startup script.  What is in /var/etc/miniupnpd.conf?  and are the interface definitions there sane?

**Comment by panda-mute** [comment]
I have meet the similar issue, my router will suddenly disappeared when eanble mwan3. If disable it, the upnp device is always there. When met such issue, try to restart firewall also can bring upnp device back.

**Comment by neheb** [comment]
Please try with the latest version.

**Comment by SirDMZ** [comment]
Can confirm. Works fine in 18.06.1

**Comment by SirDMZ** [comment]
and for some reason this bug is back... unsure what changed.

**Comment by SirDMZ** [comment]
I installed the 2.0 version of this package from lede 17 packages. works great. yes, installed in on openwrt 18.06.2

**Comment by DOCaCola** [comment]
I have experienced issues with the upnp service as well. With the help of a tool "PortMapper" (https://sourceforge.net/projects/upnp-portmapper/), i was able to figure out what was going on.

I have a OpenWRT box with IPv4/IPv6 enabled. Now i tested this with a client computer running Windows (both IPv4 and IPv6 enabled as well). When the Windows machine sends an UPNP request, miniupnp is reporting the IPv6 address of the OpenWrt box in the UPNP discovery. I have also tested this with IPv6 on the Windows machine disabled. Regardless of this, the machine gets always the IPv6 of the OpenWRT box reported. This is a big issue with many many games that only support IPv4 connections. These Programs and games will never be able to receive UPNP from OpenWRT this way. A way to improve this situation is to be able to bind miniupnpd to the IPv4 address of the interface. I think miniupnpd has this option or an option to disable IPv6 entirely, however it is not exposed through the openwrt config.

I have tested this with OpenWrt 18.06.2 using the miniupnpd 2.1-1 package.

**Comment by ffrediani** [comment]
I am not sure if this is the correct approach if I understood the question correctly. 

If the UPNP request to the router if to create a IPv4 Port Forward then it must take in consideration the IPv4 address of the requester. The same way if the PCP request if to allow a connection to be forwarded to a IPv6 device in the LAN then the IPv6 address of the requester is the one to be taken in consideration.

**Comment by neheb** [comment]
Just looked into this. It seems IPv6 support here is somewhat broken as far as the configuration goes.

I just pushed an update to https://github.com/openwrt/packages/pull/11275 .

Can anyone test?

**Comment by neheb** [comment]
I wonder if the port should be changed to 2869 for better compatibility with Windows...

**Comment by SirDMZ** [comment]
Is this available on 19.07.1 at all? If it is then I'll give it a test tonight. What would be the miniupnp package version?

**Comment by neheb** [comment]
Hrm this is strange. I can't get UPnP working on Windows.

There used to be a UPnP menu in the Network list. It's gone now. Maybe because of IPv6.

Looking at netstat, it seems it's listening on port 5000 under IPv6 only:

```
root@OpenWrt:~# netstat -ln -p | grep miniup
tcp        0      0 :::2869                 :::*                    LISTEN      5384/miniupnpd
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           5384/miniupnpd
udp        0      0 xxx.xxx.x.x:49020       0.0.0.0:*                           5384/miniupnpd
udp        0      0 xxx.xxx.x.x:5351        0.0.0.0:*                           5384/miniupnpd
udp        0      0 :::57188                :::*                                5384/miniupnpd
udp        0      0 :::1900                 :::*                                5384/miniupnpd
udp        0      0 :::5351                 :::*                                5384/miniupnpd
```

From looking at the code, a way to force it to listen to IPv4 is to pass -DV6SOCKETS_ARE_V6ONLY . Although that's used for BSDs...

**Comment by neheb** [comment]
@SirDMZ all of this is in testing. I can't just push it like this :).

**Comment by ffrediani** [comment]
Hello @neheb I am not entirely sure but Windows has been delaying a lot support for PCP and IPv6 (more precisely to IGD2).
In order to test it from Windows I have been using the miniupnpc (the client - http://miniupnp.free.fr/files/).
Yes, normally the local IPv6 gateway will be a Link-Local address. The main point is the address requested by the client is understood as from the host originating it as a client interface will normally have multiple IPv6 addresses.

**Comment by neheb** [comment]
I pushed the linked PR. Maybe someone can test in a few days...

@ffrediani are you saying that disabling igdv2 works?

**Comment by Neustradamus** [comment]
@ all: What is the status of this ticket?

**Comment by neheb** [comment]
This sounds like 18.06, which is no longer supported.
