### ISSUE TITLE
stubby: should depend on ca-certificates and/or ca-bundle ?

### ISSUE THREAD

**Issue by jonathanunderwood** [openwrt/packages#6682]
# Issue template (remove lines from top till here)

Maintainer: @iamperson347 
Environment: OpenWRT 18.06.0

Description:
I couldn't get stubby to work as initially installed. Then I noticed that ca-bundle and ca-certificates weren't installed on the system, so I used opkg to install them, and now stubby seems to be working fine. Should these be dependencies of the stubby package?

Before installing those packages and restarting stubby, I saw lots of these messages in the log:
```
Sat Aug  4 18:16:06 2018 daemon.err stubby[27773]: Could not schedule query: None of the configured upstreams could be used to send queries on the specified transports
```

**Comment by karlp** [comment]
@iamperson347 Given the readme: https://github.com/openwrt/packages/blame/master/net/stubby/files/README.md#L10-L15  yes, why wasn't this just added as a dependency of the package?

**Comment by guidosarducci** [comment]
FYI, I have some fixes and improvements for stubby (including this issue) getting ready for PR.

**Comment by iamperson347** [comment]
Hello All,

@karlp The reason I did not put ca-certificates as a dependency is because there are other ways to manage trusted certificates and I did not want to force ca-certificates on to users. This is why I put it in the openwrt-specific readme instead. However, for 90%+ of users, it probably makes sense to simply make ca-certificates a dependency.

@guidosarducci Please link the PR so we can see what fixes/improvements you are proposing.

**Comment by karlp** [comment]
honestly, the fact that you _could_ manage certificates manually is irrelevant.  It would be true of all dependencies of all packages.

**Comment by iamperson347** [comment]
I have seen other openwrt packages that potentially depend on SSL/TLS connectivity that did not have a ca-cert dependency. However, per your recommendation, we can include it. For this package, since it _requires_ SSL connectivity, it makes sense.

**Comment by karlp** [comment]
If you can find other packages that _depend_ on certs in some form, and are not optional, then please just straight up file tickets on them.

**Comment by cshoredaniel** [comment]
@iamperson347 Can you check of (in master) ca-bundle is all you need? Another contributor had a PR that modified ca-bundle so that openssl and mbedtls should hopefully not need ca-certificates, and ca-bundle is smaller due to less file metadata, and on a number of supported devices this matters.

**Comment by iamperson347** [comment]
@cshoredaniel I think that should work. I will have to check it, but I believe stubby (and the getdns library) use openssl for SSL connectivity and ca-bundle appears to have the the root CA that cloudflare's intermediate and cert hang off of.

**Comment by guidosarducci** [comment]
@cshoredaniel Hi Daniel, IIRC you were also looking into the issues around bundled vs. unbundled certs. Is there a prospect of -- or timeline for -- standardizing on use of `ca-bundle` in OpenWrt due to its smaller size?

Until that can happen, installations might be using bundled or unbundled certs, and a hard `stubby` dependency on either package would often just consume users' flash needlessly. For that reason, I'm now leaning towards having stubby support using either `ca-certificates` or `ca-bundle` (needs a fix) if present, without hard-coding a dependency.

**Comment by cshoredaniel** [comment]
@guidosarducci I'm glad you found the commit ... I mentioned somewhere else you mentioned me.  Sorry for not getting back sooner.  rl's been busy.
