### ISSUE TITLE
upmpdcli: no home directory created

### ISSUE THREAD

**Issue by ralemb** [openwrt/packages#715]
upmpdcli is running as user upmpdcli.
User upmpdcli should have home /var/run/upmpdcli, but there's no such directory.

Is this intended?

**Comment by thess** [comment]
Short answer - yes it is OK as is.

Upon code inspection -- it turns out if upmpdcli is launched as **root** and then executes setuid to user *upmpdcli*, the cache directory will be /var/cache/upmpdcli. The home directory ($HOME) is only used when actually logged into user *upmpdcli* which is not the case here.

**Comment by ralemb** [comment]
Thank You.
