### ISSUE TITLE
ddns-scripts_route53-v1: request rejected because Route53 is processing a prior request

### ISSUE THREAD

**Issue by mark0n** [openwrt/packages#7492]
### Maintainer
@chris5560, @maxberger
### Environment
OpenWRT 18.06.0
DDNS version: 2.7.8-5

### Description
I have multiple host names that need to be updated using the Route53 DDNS script. After starting the scripts only one or two of them are submitting their first update to Route53 successfully. The others fail with the following message:
```
...<Code>PriorRequestNotComplete</Code><Message>The request was rejected because Route 53 was still processing a prior request.</Message>...
```

After 5 min the scripts retry and one or two more succeed. Eventually they all go to normal. Seems like this issue only occurs when too many _updates_ occur within a short time. _Checking_ the IP address doesn't seem to be an issue.

Turns out I'm hitting a [limit documented in the Route53 documentation](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests-route-53). Not sure if the script could prevent this somehow. (Maybe by sharing a lock (flock?) between all the instances of `ddns-scripts_route53-v1` that ensures only one of them is requesting an update at a time?)

**Comment by maxberger** [comment]
Hi Martin,

In first glance a shared lock sounds like it could work. I don't know if
there are any "openwrt standards" regarding this.

The proper way to get this included would be if you try to solve the issue
and create a pull request. I can then test your changes to ensure that also
work on a different system, Chris is the main maintainer here.

Max


Am 21.11.2018 09:52 schrieb "Martin Konrad" <notifications@github.com>:

Maintainer

@chris5560 <https://github.com/chris5560>, @maxberger
<https://github.com/maxberger>
Environment

OpenWRT 18.06.0
DDNS version: 2.7.8-5
Description

I have multiple host names that need to be updated using the Route53 DDNS
script. After starting the scripts only one or two of them are submitting
their first update to Route53 successfully. The others fail with the
following message:

...<Code>PriorRequestNotComplete</Code><Message>The request was
rejected because Route 53 was still processing a prior
request.</Message>...

After 5 min the scripts retry and one or two more succeed. Eventually they
all go to normal. Seems like this issue only occurs when too many *updates*
occur within a short time. *Checking* the IP address doesn't seem to be an
issue.

Turns out I'm hitting a limit documented in the Route53 documentation
<https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests-route-53>.
Not sure if the script could prevent this somehow. (Maybe by sharing a lock
(flock?) between all the instances of ddns-scripts_route53-v1 that ensures
only one of them is requesting an update at a time?)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openwrt/packages/issues/7492>, or mute the thread

**Comment by mark0n** [comment]
Locking solves the problem reliably for me.

**Comment by maxberger** [comment]
Great! Can you create a pull request?

Am Fr., 23. Nov. 2018, 23:08 hat Martin Konrad <notifications@github.com>
geschrieben:
