### ISSUE TITLE
openssh: scp client vulnerabilities

### ISSUE THREAD

**Issue by ja-pa** [openwrt/packages#7961]
Openssh scp client suffers for multiple vulnerabilities related to malicious scp server. 
Full advisory https://sintonen.fi/advisories/scp-client-multiple-vulnerabilities.txt

@tripolar Do you think it's worth patching?

https://security-tracker.debian.org/tracker/CVE-2019-6110
https://security-tracker.debian.org/tracker/CVE-2019-6109
https://security-tracker.debian.org/tracker/CVE-2019-6111

**Comment by BKPepe** [comment]
@tripolar Thank you for fixing CVE-2019-6111 by this commit https://github.com/openwrt/packages/commit/d92d34db5a382997e3d9230247644e55a1d84602!

**Comment by BKPepe** [comment]
Just for reference. Commit https://github.com/openwrt/packages/commit/4729c3fddf05d6c8496ac2602a843e7dce5990e4#diff-7e78486312acc037feda42e1bea3dfc6 was applied applied to master (and it is already present in openwrt-19.07 branch). But the issue is still present in openwrt-18.06, there is a version of openssh 7.7p1, that's why I'm reopening it.

**Comment by neheb** [comment]
@ja-pa I don't see why not.

**Comment by BKPepe** [comment]
@ja-pa Would you please create pull request for OpenWrt 18.06?

**Comment by cotequeiroz** [comment]
18.06 is EOL, so I'm closing this.
