### ISSUE TITLE
miniupnpd prints help message and don't want to start

### ISSUE THREAD

**Issue by andrew-aladev** [openwrt/packages#858]
I've installed miniupnpd on MR3020 from 14.07 release

```
sudo /etc/init.d/miniupnpd start
> Usage: ...
sudo /usr/sbin/miniupnpd -f /var/etc/miniupnpd.conf -d
> Usage: ...
```

`/var/etc/miniupnpd.conf`:
```
ext_ifname=3g-3g
port=5000
enable_natpmp=yes
enable_upnp=yes
secure_mode=yes
pcp_allow_thirdparty=no
system_uptime=yes
lease_file=/var/upnp.leases
bitrate_down=8388608
bitrate_up=4194304
uuid=42cef3f0-2b30-4f96-9685-29bb28a1f7f8
allow 1024-65535 0.0.0.0/0 1024-65535
deny 0-65535 0.0.0.0/0 0-65535
```

What is going on? It looks like miniupnpd build is completely broken.

**Comment by thess** [comment]
It seems from this output that the internal lan interface is not available. There is no listening_ip (interface) in the output you provided.

I suspect the problem lies in your network config and/or miniupnpd defaults. Could you please supply some additional data:

* Output from 'ifconfig'
* Contents of /etc/config/upnpd
* Contents of /etc/config/network and /etc/config/wireless.

**Comment by andrew-aladev** [comment]
Oh. The problem was `option internal_iface 'lan'`. I've changed it to `option internal_iface 'LAN'` and miniupnpd started working.
